-- ============================================================
-- Migración: agregar columna UUID a las tablas que no la tenían
-- Base de datos: gestion-academica-cmm (MySQL)
--
-- Ejecutar ESTE SCRIPT COMPLETO una sola vez.
-- ============================================================

-- 1. Agregar la columna UUID (CHAR(36), nullable temporalmente)
ALTER TABLE T_VIGENCIA            ADD COLUMN VIG_UUID         CHAR(36) NULL AFTER VIG_ID;
ALTER TABLE T_DIA_SEMANA          ADD COLUMN DIA_SEM_UUID     CHAR(36) NULL AFTER DIA_SEM_ID;
ALTER TABLE T_MATERIA             ADD COLUMN MAT_UUID         CHAR(36) NULL AFTER MAT_ID;
ALTER TABLE T_NIVEL_EDUCATIVO     ADD COLUMN NIV_EDUC_UUID    CHAR(36) NULL AFTER NIV_EDUC_ID;
ALTER TABLE T_GRADO               ADD COLUMN GRAD_UUID        CHAR(36) NULL AFTER GRAD_ID;
ALTER TABLE T_TIPO_COMPONENTE     ADD COLUMN TIPO_COMP_UUID   CHAR(36) NULL AFTER TIPO_COMP_ID;
ALTER TABLE T_COMPONENTE_EVALUATIVO ADD COLUMN COM_EVA_UUID   CHAR(36) NULL AFTER COM_EVA_ID;

-- 2. Poblar con UUID los registros existentes
UPDATE T_VIGENCIA            SET VIG_UUID       = UUID() WHERE VIG_UUID       IS NULL;
UPDATE T_DIA_SEMANA          SET DIA_SEM_UUID   = UUID() WHERE DIA_SEM_UUID   IS NULL;
UPDATE T_MATERIA             SET MAT_UUID       = UUID() WHERE MAT_UUID       IS NULL;
UPDATE T_NIVEL_EDUCATIVO     SET NIV_EDUC_UUID  = UUID() WHERE NIV_EDUC_UUID  IS NULL;
UPDATE T_GRADO               SET GRAD_UUID      = UUID() WHERE GRAD_UUID      IS NULL;
UPDATE T_TIPO_COMPONENTE     SET TIPO_COMP_UUID = UUID() WHERE TIPO_COMP_UUID IS NULL;
UPDATE T_COMPONENTE_EVALUATIVO SET COM_EVA_UUID = UUID() WHERE COM_EVA_UUID   IS NULL;

-- 3. Hacerlas NOT NULL y únicas
ALTER TABLE T_VIGENCIA            MODIFY COLUMN VIG_UUID       CHAR(36) NOT NULL;
ALTER TABLE T_DIA_SEMANA          MODIFY COLUMN DIA_SEM_UUID   CHAR(36) NOT NULL;
ALTER TABLE T_MATERIA             MODIFY COLUMN MAT_UUID       CHAR(36) NOT NULL;
ALTER TABLE T_NIVEL_EDUCATIVO     MODIFY COLUMN NIV_EDUC_UUID  CHAR(36) NOT NULL;
ALTER TABLE T_GRADO               MODIFY COLUMN GRAD_UUID      CHAR(36) NOT NULL;
ALTER TABLE T_TIPO_COMPONENTE     MODIFY COLUMN TIPO_COMP_UUID CHAR(36) NOT NULL;
ALTER TABLE T_COMPONENTE_EVALUATIVO MODIFY COLUMN COM_EVA_UUID CHAR(36) NOT NULL;

ALTER TABLE T_VIGENCIA            ADD UNIQUE INDEX UQ_VIG_UUID         (VIG_UUID);
ALTER TABLE T_DIA_SEMANA          ADD UNIQUE INDEX UQ_DIA_SEM_UUID     (DIA_SEM_UUID);
ALTER TABLE T_MATERIA             ADD UNIQUE INDEX UQ_MAT_UUID         (MAT_UUID);
ALTER TABLE T_NIVEL_EDUCATIVO     ADD UNIQUE INDEX UQ_NIV_EDUC_UUID    (NIV_EDUC_UUID);
ALTER TABLE T_GRADO               ADD UNIQUE INDEX UQ_GRAD_UUID        (GRAD_UUID);
ALTER TABLE T_TIPO_COMPONENTE     ADD UNIQUE INDEX UQ_TIPO_COMP_UUID   (TIPO_COMP_UUID);
ALTER TABLE T_COMPONENTE_EVALUATIVO ADD UNIQUE INDEX UQ_COM_EVA_UUID   (COM_EVA_UUID);

-- ============================================================
-- 4. VERIFICACIÓN de las 15 tablas que ya tenían UUID generado
--    desde el INSERT (solo para comprobar que existen).
--    Si alguna falla, agrégala manualmente con el mismo patrón.
-- ============================================================
-- T_PERSONA              (PER_UUID)
-- T_ESTUDIANTE           (EST_UUID)
-- T_DOCENTE              (DOC_UUID)
-- T_ACUDIENTE            (ACU_UUID)
-- T_ACUDIENTE_CORREO     (ACU_CORR_UUID)
-- T_ACUDIENTE_TELEFONO   (ACU_TEL_UUID)
-- T_ACUDIENTE_ESTUDIANTE (ACU_EST_UUID)
-- T_ROL                  (ROL_UUID)  <-- el servicio no lo insertaba, ya corregido
-- T_MATRICULA            (MATR_UUID)
-- T_CURSO_VIGENCIA       (CUR_VIG_UUID)
-- T_PERIODO_ACADEMICO    (PER_ACA_UUID)
-- T_ASIGNACION_ACADEMICA (ASIG_ACA_UUID)
-- T_ACTIVIDAD_EVALUATIVA (ACT_EVA_UUID)
-- T_RESULTADO_EVALUATIVO (RES_EVA_UUID)
-- T_DETALLE_HORARIO      (DET_HOR_UUID)
